package com.card.component;

import static com.card.component.CardComponent.Architype;
import static com.card.component.HexCode.*;

public enum ArchitypeComponent implements CardSubcomponentInterface {
	AllyOfJustice_A(Hex_1), Genex_A(Hex_2), RGenex_A(Hex_100_2), GenexAlly_A(Hex_200_2), Horus_A(Hex_3),
	HorusBlackFlameDragon_A(Hex_100_3), Amazoness_A(Hex_4), ArcanaForce_A(Hex_5), DarkWorld_A(Hex_6), AncientGear_A(Hex_7),
	Hero_A(Hex_8), ElementalHero_A(Hex_300_8), VisionHero_A(Hex_500_8), EvilHero_A(Hex_600_8), MaskedHero_A(Hex_A00_8),
	DestinyHero_A(Hex_C00_8), Neos_A(Hex_9), Lswarm_A(Hex_A), Steelswarm_A(Hex_100_A), Infernity_A(Hex_B), Alien_A(Hex_C),
	Saber_A(Hex_D), XSaber_A(Hex_100_D), XxSaber_A(Hex_300_D), Elementsaber_A(Hex_400_D), Watt_A(Hex_E), Ojama_A(Hex_F),
	Gusto_A(Hex_10), Karakuri_A(Hex_11), Frog_A(Hex_12), Meklord_A(Hex_13), MeklordEmperor_A(Hex_30_13), MeklordArmy_A(Hex_60_13),
	MeklordAstro_A(Hex_90_13), AllureQueen_A(Hex_14), Bes_A(Hex_15), Roid_A(Hex_16), Vehicroid_A(Hex_10_16), Speedroid_A(Hex_20_16),
	Synchro_A(Hex_17), Synchron_A(Hex_10_17), SynchroDragon_A(Hex_20_17), Cloudian_A(Hex_18), Gladiator_A(Hex_19),
	GladiatorBeast_A(Hex_10_19), DarkScorpion_A(Hex_1A), PhantomBeast_A(Hex_1B), MechaPhantomBeast_A(Hex_10_1B),
	SpiritMessage_A(Hex_1C), KoakiMeiru_A(Hex_1D), Chrysalis_A(Hex_1E), NeoSpacian_A(Hex_1F), Shien_A(Hex_20), Earthbound_A(Hex_21),
	EarthboundImmortal_A(Hex_10_21), Jurrac_A(Hex_22), Malefic_A(Hex_23), Scrap_A(Hex_24), IronChain_A(Hex_25),
	Morphtronic_A(Hex_26), Tg_A(Hex_27), Batteryman_A(Hex_28), Dragunity_A(Hex_29), Naturia_A(Hex_2A), Ninja_A(Hex_2B),
	Flamvell_A(Hex_2C), Nitro_A(Hex_2D), Gravekeepers_A(Hex_2E), IceBarrier_A(Hex_2F), Vylon_A(Hex_30), FortuneLady_A(Hex_31),
	Volcanic_A(Hex_32), Blackwing_A(Hex_33), AssaultBlackwing_A(Hex_10_33), Crystal_A(Hex_34), CrystalBeast_A(Hex_10_34),
	UltimateCrystal_A(Hex_20_34), AdvancedCrystalBeast_A(Hex_50_34), Fabled_A(Hex_35), Machina_A(Hex_36), MistValley_A(Hex_37),
	Lightsworn_A(Hex_38), Laval_A(Hex_39), Gishki_A(Hex_3A), RedEyes_A(Hex_3B), Reptilianne_A(Hex_3C), SixSamurai_A(Hex_3D),
	SecretSixSamurai_A(Hex_10_3D), Worm_A(Hex_3E), Majestic_A(Hex_3F), ForbiddenOne_A(Hex_40), Lv_A(Hex_41), Nordic_A(Hex_42),
	NordicAscendant_A(Hex_30_42), NordicBeast_A(Hex_60_42), NordicAlfar_A(Hex_A0_42), NordicRelic_A(Hex_50_42), Junk_A(Hex_43),
	TheAgent_A(Hex_44), Archfiend_A(Hex_45), RedDragonArchfiend_A(Hex_10_45), Fusion_A(Hex_46), FusionDragon_A(Hex_10_46),
	Gem_A(Hex_47), GemKnight_A(Hex_10_47), Number_A(Hex_48), NumberC_A(Hex_10_48), NumberC39_A(Hex_50_48), Skyblaster_A(Hex_49),
	Timelord_A(Hex_4A), Aesir_A(Hex_4B), TrapHole_A(Hex_4C), BeastsBattle_A(Hex_4D), Evoltile_A(Hex_30_4E), Evolsaur_A(Hex_60_4E),
	Evolzar_A(Hex_50_4E), DarkLucius_A(Hex_4F), AssaultMode_A(Hex_10_4F), Venom_A(Hex_50), StarvingVenom_A(Hex_10_50),
	Gadget_A(Hex_51), Guardian_A(Hex_52), GateGuardian_A(Hex_10_52), SkullGuardian_A(Hex_20_52), Constellar_A(Hex_53),
	Gagaga_A(Hex_54), Photon_A(Hex_55), Inzektor_A(Hex_56), Resonator_A(Hex_57), WindUp_A(Hex_58), Gogogo_A(Hex_59),
	Penguin_A(Hex_5A), Inmato_A(Hex_5B), Sphinx_A(Hex_5C), UltimateInsect_A(Hex_5D), DarkMimic_A(Hex_5E), MysticSwordsman_A(Hex_5F),
	BambooSword_A(Hex_60), NinjitsuArt_A(Hex_61), Toon_A(Hex_62), Reactor_A(Hex_63), Harpie_A(Hex_64), Infestation_A(Hex_65),
	Warrior_A(Hex_66), SymphonicWarrior_A(Hex_10_66), MagnetWarrior_A(Hex_20_66), Hieratic_A(Hex_69), Butterspy_A(Hex_6A),
	Bounzer_A(Hex_6B), Helios_A(Hex_6C), Djinn_A(Hex_6D), Prophecy_A(Hex_6E), Spellbook_A(Hex_10_6E), Heroic_A(Hex_6F),
	HeroicChallenger_A(Hex_10_6F), HeroicChampion_A(Hex_20_6F), Chronomaly_A(Hex_70), Madolche_A(Hex_71), Geargia_A(Hex_72),
	Geargiano_A(Hex_10_72), Xyz_A(Hex_73), Cxyz_A(Hex_10_73), XyzDragon_A(Hex_20_73), ArmoredXyz_A(Hex_40_73), Mermail_A(Hex_74),
	Abyss_A(Hex_75), HeraldicBeast_A(Hex_76), Atlantean_A(Hex_77), Nimble_A(Hex_78), FireFist_A(Hex_79), NobleKnight_A(Hex_10_7A),
	InfernobleKnight_A(Hex_50_7A), NobleArms_A(Hex_20_7A), InfernobleArms_A(Hex_60_7A), Galaxy_A(Hex_7B), GalaxyEyes_A(Hex_10_7B),
	GalaxyEyesTachyonDragon_A(Hex_30_7B), FireFormation_A(Hex_7C), Hazy_A(Hex_7D), HazyFlame_A(Hex_10_7D), Zexal_A(Hex_7E),
	Zw_A(Hex_10_7E), Zs_A(Hex_20_7E), Utopic_A(Hex_7F), Utopia_A(Hex_10_7F), UtopicFuture_A(Hex_20_7F), Duston_A(Hex_80),
	FireKing_A(Hex_81), FireKingAvatar_A(Hex_10_81), Dododo_A(Hex_82), Puppet_A(Hex_83), GimmickPuppet_A(Hex_10_83),
	BattlinBoxer_A(Hex_84), SuperDefenseRobot_A(Hex_85), StarSeraph_A(Hex_86), UmbralHorror_A(Hex_87), Bujin_A(Hex_88),
	Hole_A(Hex_89), Traptrix_A(Hex_10_8A), Malicevorous_A(Hex_8B), Ghostrick_A(Hex_8D), Vampire_A(Hex_8E), Zubaba_A(Hex_8F),
	Sylvan_A(Hex_90), Necrovalley_A(Hex_91), Heraldry_A(Hex_92), Cyber_A(Hex_93), CyberDragon_A(Hex_10_93), CyberAngel_A(Hex_20_93),
	Cyberdark_A(Hex_40_93), Cybernetic_A(Hex_94), RankUpMagic_A(Hex_95), Fishborg_A(Hex_96), Artifact_A(Hex_97), Magician_A(Hex_98),
	OddEyes_A(Hex_99), SuperheavySamurai_A(Hex_9A), SuperheavySamuraiSoul_A(Hex_1_09A), Melodious_A(Hex_9B),
	MelodiousMaestra_A(Hex_10_9B), Tellarknight_A(Hex_9C), Stellarknight_A(Hex_10_9C), Shaddoll_A(Hex_9D), YangZing_A(Hex_9E),
	Performapal_A(Hex_9F), LegendaryKnight_A(Hex_A0), LegendaryDragon_A(Hex_A1), DarkMagician_A(Hex_10_A2),
	MagicianGirl_A(Hex_20_A2), DarkMagicianGirl_A(Hex_30_A2), Stardust_A(Hex_A3), Kuriboh_A(Hex_A4), WingedKuriboh_A(Hex_10_A4),
	Change_A(Hex_A5), Sprout_A(Hex_A6), Artorigus_A(Hex_A7), Laundsallyn_A(Hex_A8), Fluffal_A(Hex_A9), Qli_A(Hex_Aa),
	Apoqliphort_A(Hex_10_Aa), Deskbot_A(Hex_Ab), Goblin_A(Hex_Ac), GoblinRider_A(Hex_10_Ac), Frightfur_A(Hex_Ad),
	DarkContract_A(Hex_Ae), Dd_A(Hex_Af), Ddd_A(Hex_10_Af), Gottoms_A(Hex_B0), BurningAbyss_A(Hex_B1), Ua_A(Hex_B2),
	Yosenju_A(Hex_B3), Nekroz_A(Hex_B4), RitualBeast_A(Hex_B5), RitualBeastTamer_A(Hex_10_B5), SpiritualBeast_A(Hex_20_B5),
	SpiritualBeastTamer_A(Hex_30_B5), RitualBeastUlti_A(Hex_40_B5), OuterEntity_A(Hex_10_B7), ElderEntity_A(Hex_20_B7),
	OldEntity_A(Hex_40_B7), BlazeAccelerator_A(Hex_B9), Raidraptor_A(Hex_Ba), Infernoid_A(Hex_Bb), Jinzo_A(Hex_Bc),
	GaiaTheFierceKnight_A(Hex_Bd), Monarch_A(Hex_Be), Charmer_A(Hex_Bf), Possessed_A(Hex_C0), FamiliarPossessed_A(Hex_10_C0),
	PsyFrame_A(Hex_C1), PsyFramegear_A(Hex_10_C1), PowerTool_A(Hex_C2), EdgeImp_A(Hex_C3), Zefra_A(Hex_C4), Void_A(Hex_C5),
	Performage_A(Hex_C6), Dracoslayer_A(Hex_C7), Igknight_A(Hex_C8), Aroma_A(Hex_C9), EmpoweredWarrior_A(Hex_Ca), Aether_A(Hex_Cb),
	PredictionPrincess_A(Hex_Cc), Aquaactress_A(Hex_10_Cd), Aquarium_A(Hex_20_Cd), Chaos_A(Hex_Cf),
	BlackLusterSoldier_A(Hex_10_Cf), Majespecter_A(Hex_D0), Graydle_A(Hex_D1), Kozmo_A(Hex_D2), Kaiju_A(Hex_D3),
	Paleozoic_A(Hex_D4), Dante_A(Hex_D5), DestructionSword_A(Hex_D6), BusterBlader_A(Hex_D7), Dinomist_A(Hex_D8),
	Shiranui_A(Hex_D9), ShiranuiSpectralsword_A(Hex_10_D9), Dracoverlord_A(Hex_Da), PhantomKnights_A(Hex_Db),
	ThePhantomKnights_A(Hex_10_Db), SuperQuant_A(Hex_Dc), SuperQuantum_A(Hex_10_Dc), SuperQuantalMechBeast_A(Hex_20_Dc),
	BlueEyes_A(Hex_Dd), Exodia_A(Hex_De), Lunalight_A(Hex_Df), Amorphage_A(Hex_E0), Metalfoes_A(Hex_E1), Triamid_A(Hex_E2),
	Cubic_A(Hex_E3), CelticGuard_A(Hex_E4), Cipher_A(Hex_E5), CipherDragon_A(Hex_10_E5), FlowerCardian_A(Hex_E6),
	SilentSwordsman_A(Hex_E7), SilentMagician_A(Hex_E8), MagnaWarrior_A(Hex_E9), Crystron_A(Hex_Ea), Chemicritter_A(Hex_Eb),
	AbyssActor_A(Hex_10_Ec), AbyssScript_A(Hex_20_Ec), Subterror_A(Hex_Ed), SubterrorBehemoth_A(Hex_10_Ed), Spyral_A(Hex_Ee),
	SpyralGear_A(Hex_10_Ee), SpyralMission_A(Hex_20_Ee), Darklord_A(Hex_Ef), Windwitch_A(Hex_F0), Zoodiac_A(Hex_F1),
	Pendulum_A(Hex_F2), PendulumDragon_A(Hex_10_F2), Pendulumgraph_A(Hex_20_F2), Predap_A(Hex_F3), Predaplant_A(Hex_10_F3),
	Invoked_A(Hex_F4), Gandora_A(Hex_F5), Skyscraper_A(Hex_F6), Lyrilusc_A(Hex_F7), SupremeKingGate_A(Hex_10_F8),
	SupremeKingDragon_A(Hex_20_F8), TrueDracoKing_A(Hex_F9), PhantasmSpiral_A(Hex_Fa), Trickstar_A(Hex_Fb), Gouki_A(Hex_Fc),
	WorldChalice_A(Hex_Fd), WorldLegacy_A(Hex_Fe), ClearWing_A(Hex_Ff), Bonding_A(Hex_100), CodeTalker_A(Hex_101),
	Rokket_A(Hex_102), Altergeist_A(Hex_103), Krawler_A(Hex_104), Metaphys_A(Hex_105), Vendread_A(Hex_106), Fa_A(Hex_107),
	MagicalMusket_A(Hex_108), TheWeather_A(Hex_109), Parshath_A(Hex_10A), Tindangle_A(Hex_10B), MekkKnight_A(Hex_10C),
	MythicalBeast_A(Hex_10D), EvolutionPill_A(Hex_10E), Borrel_A(Hex_10F), Relinquished_A(Hex_110), EyesRestrict_A(Hex_1_110),
	ArmedDragon_A(Hex_111), ArmedDragonThunder_A(Hex_1_111), Knightmare_A(Hex_112), ElementalLord_A(Hex_113), FurHire_A(Hex_114),
	SkyStriker_A(Hex_115), SkyStrikerAce_A(Hex_1_115), Crusadia_A(Hex_116), Impcantation_A(Hex_117), Cynet_A(Hex_118),
	Salamangreat_A(Hex_119), Dinowrestler_A(Hex_11A), Orcust_A(Hex_11B), ThunderDragon_A(Hex_11C), Forbidden_A(Hex_11D),
	Danger_A(Hex_11E), Nephthys_A(Hex_11F), PrankKids_A(Hex_120), Mayakashi_A(Hex_121), Valkyrie_A(Hex_122), Rose_A(Hex_123),
	RoseDragon_A(Hex_1_123), MachineAngel_A(Hex_124), Smile_A(Hex_125), TimeThief_A(Hex_126), Infinitrack_A(Hex_127),
	Witchcrafter_A(Hex_128), EvilEye_A(Hex_129), Endymion_A(Hex_12A), Marincess_A(Hex_12B), Tenyi_A(Hex_12C), Simorgh_A(Hex_12D),
	FortuneFairy_A(Hex_12E), Battlewasp_A(Hex_12F), Unchained_A(Hex_130), UnchainedSoul_A(Hex_1_130), DreamMirror_A(Hex_131),
	Mathmech_A(Hex_132), Dragonmaid_A(Hex_133), Generaider_A(Hex_134), Ignister_A(Hex_135), Ai_A(Hex_136),
	AncientWarriors_A(Hex_137), Megalith_A(Hex_138), Onomat_A(Hex_139), Palladium_A(Hex_13A), Rebellion_A(Hex_13B),
	Codebreaker_A(Hex_13C), Nemeses_A(Hex_13D), Barbaros_A(Hex_13E), PlunderPatroll_A(Hex_13F), Adamancipator_A(Hex_140),
	Rikka_A(Hex_141), Eldlich_A(Hex_142), Eldlixir_A(Hex_143), GoldenLand_A(Hex_144), Phantasm_A(Hex_145), Dogmatika_A(Hex_146),
	Melffy_A(Hex_147), Potan_A(Hex_148), Roland_A(Hex_149), Appliancer_A(Hex_14A), Numeron_A(Hex_14B), NumeronGate_A(Hex_1_14B),
	Fossil_A(Hex_14C), SpiritualEarthArt_A(Hex_3_14D), SpiritualFireArt_A(Hex_5_14D), SpiritualWaterArt_A(Hex_6_14D),
	SpiritualWindArt_A(Hex_A_14D), DualAvatar_A(Hex_14E), TriBrigade_A(Hex_14F), VirtualWorld_A(Hex_150),
	VirtualWorldGate_A(Hex_1_150), Drytron_A(Hex_151), Magistus_A(Hex_152), KiSikil_A(Hex_153), LilLa_A(Hex_154),
	EvilTwin_A(Hex_155), LiveTwin_A(Hex_156), Sunavalon_A(Hex_1_157), Sunvine_A(Hex_2_157), Sunseed_A(Hex_4_157),
	Springans_A(Hex_158), Myutant_A(Hex_159), SForce_A(Hex_15A), StarryKnight_A(Hex_15B), DollMonster_A(Hex_15C),
	RankDownMagic_A(Hex_15D), Amazement_A(Hex_15E), Attraction_A(Hex_15F), Branded_A(Hex_160), WarRock_A(Hex_161),
	Materiactor_A(Hex_162), Ogdoadic_A(Hex_163), Solfachord_A(Hex_164), Gransolfachord_A(Hex_1_164), Ursarctic_A(Hex_165),
	Despia_A(Hex_166), Magikey_A(Hex_167), Gunkan_A(Hex_168), MysticalBeastOfTheForest_A(Hex_1_169),
	MysticalSpiritOfTheForest_A(Hex_2_169), StealthKragen_A(Hex_16A), Numerounious_A(Hex_16B), NumberSpellTrap_A(Hex_16C),
	Swordsoul_A(Hex_16D), Icejade_A(Hex_16E), Floowandereeze_A(Hex_16F), Topologic_A(Hex_170), Hyperion_A(Hex_171),
	Beetrooper_A(Hex_172), Punk_A(Hex_173), Exosister_A(Hex_174), Dinomorphia_A(Hex_175), LadyOfLament_A(Hex_176),
	Seventh_A(Hex_177), Barians_A(Hex_1_178), Battleguard_A(Hex_2_178), KairyuShin_A(Hex_179), SeaStealth_A(Hex_17A),
	Therion_A(Hex_17B), Scareclaw_A(Hex_17C), Libromancer_A(Hex_17D), Vaylantz_A(Hex_17E), Labrynth_A(Hex_17F),
	WelcomeLabrynth_A(Hex_1_17F), Runick_A(Hex_180), Spright_A(Hex_181), Tearlaments_A(Hex_182), Vernusylph_A(Hex_183),
	MokeyMokey_A(Hex_184), Wingman_A(Hex_185), DoodleBeast_A(Hex_1_186), Doodlebook_A(Hex_2_186), GGolem_A(Hex_187),
	RainbowBridge_A(Hex_188), Bystial_A(Hex_189), Ghoti_A(Hex_18B), Kashtira_A(Hex_18A), GoldPride_A(Hex_193), Koala_A(Hex_67),
	Kangaroo_A(Hex_68), RescueAce_A(Hex_18C), Purrely_A(Hex_18D), Mikanko_A(Hex_18E), Aquamirror_A(Hex_18F), Firewall_A(Hex_190),
	Mannadium_A(Hex_191), Nemleria_A(Hex_192), LabyrinthWall_A(Hex_194), Favorite_A(Hex_195), VanquishSoul_A(Hex_196),
	Nouvelles_A(Hex_197), Recipe_A(Hex_198), Visas_A(Hex_199), Memento_A(Hex_19A), Centurion_A(Hex_19B), Vaalmonica_A(Hex_19C),
	Yubel_A(Hex_19D), VoicelessVoice_A(Hex_19E), Toy_A(Hex_1A0), TenpaiDragon_A(Hex_1A1), Sangen_A(Hex_1A2), Ragnaraika_A(Hex_1A3),
	Millennium_A(Hex_1A6), Exodd_A(Hex_1A7), Fiendsmith_A(Hex_1A8), WhiteForest_A(Hex_1Aa), Mulcharmy_A(Hex_1Ac),
	Emblema_A(Hex_1Ad), Counter_A(Hex_200), BattlinBoxing_A(Hex_201), Veda_A(Hex_202), Diabell_A(Hex_203),
	Diabellestar_A(Hex_1_203), SinfulSpoils_A(Hex_204), SnakeEye_A(Hex_205), Patissciel_A(Hex_206), Heart_A(Hex_207),
	Tistina_A(Hex_208), WhiteAura_A(Hex_1_19F), Salamandra_A(Hex_1A4), Ashened_A(Hex_1A5), BlueTears_A(Hex_1A9), Tachyon_A(Hex_1Ab),
	Shark_A(Hex_1Ae), SharkDrake_A(Hex_1_1Ae), Wedju_A(Hex_1Af), Primite_A(Hex_1B0), SixStrike_A(Hex_1B1), Metalmorph_A(Hex_1B2),
	Morganite_A(Hex_1B3), Azamina_A(Hex_1B4), Mimighoul_A(Hex_1B5), Ryzeal_A(Hex_1B6), Schoolwork_A(Hex_1B7), RyuGe_A(Hex_1B8),
	Maliss_A(Hex_1B9), Argostars_A(Hex_1Ba), AquaJet_A(Hex_1Bb), DragonRuler_A(Hex_1Bc), Mitsurugi_A(Hex_1Bd), Dominus_A(Hex_1Bf),
	Apophis_A(Hex_1C2), Serket_A(Hex_1C3),;

	private final CardComponent cardComponent = Architype;
	private final HexCode hexCode;

	private ArchitypeComponent(HexCode hexCode) {
		this.hexCode = hexCode;
	}

	@Override
	public String getComponentName() {
		return cardComponent.getComponentName();
	}

	public HexCode getHexCode() {
		return this.hexCode;
	}
}
