# Apply to all loggers
.level = ALL
handlers = yugioh.logging.builtin.JsonStreamFileHandler

# Handler config
yugioh.logging.builtin.JsonStreamFileHandler.level = ALL
yugioh.logging.builtin.JsonStreamFileHandler.formatter = yugioh.logging.builtin.JsonFormatter
yugioh.logging.builtin.JsonStreamFileHandler.filename = yugioh/logging/logs/javaLog.json
